services:
  db:
    image: postgres:16
    environment:
      - POSTGRES_DB=asai
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odoo -d asai"]
      interval: 10s
      timeout: 5s
      retries: 10

  odoo:
    image: odoo:18.0
    depends_on:
      db:
        condition: service_healthy
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    ports:
      - "8069:8069"
    volumes:
      - ./addons:/mnt/extra-addons
      - odoo_data:/var/lib/odoo

volumes:
  pgdata:
  odoo_data:
